## Análise Exploratória de Dados (EDA)
### Microdados ENEM 2025

#### Bibliotecas utilizadas

In [ ]:
import pandas as pd

#### Análise sobre os participantes

In [2]:
df_partcipantes = pd.read_csv("../data/PARTICIPANTES_2025.csv", sep=";", encoding="iso-8859-1")
df_partcipantes.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,...,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023
0,210066506229,2025,6,F,1,2,2,1,4,NaN,...,A,A,A,A,A,A,A,A,B,A
1,210066506230,2025,3,M,1,1,1,2,0,1.0,...,A,B,B,A,C,A,B,B,B,A
2,210066506231,2025,2,F,1,1,1,3,0,NaN,...,A,A,B,A,A,A,B,C,C,C
3,210066506232,2025,2,M,1,3,2,2,0,1.0,...,A,B,A,A,B,A,B,B,D,D
4,210066506233,2025,1,F,1,1,1,3,0,NaN,...,B,B,B,B,D,B,B,D,E,D

In [3]:
# Quantos participantes realizaram o ENEM 2025?
qtde_participantes = len(df_partcipantes)
print(f"Quantidade total de participantes: {qtde_participantes:,}")

Quantidade total de participantes: 4,810,772

In [4]:
# Qual a distribuição de participantes por Estado?
(df_partcipantes["SG_UF_PROVA"]
 .value_counts()
 .sort_index()
 )

SG_UF_PROVA
AC     28957
AL     96480
AM    110831
AP     33190
BA    427983
CE    275902
DF     82955
ES     85910
GO    166747
MA    211370
MG    464937
MS     57932
MT     80396
PA    289328
PB    142035
PE    272279
PI    120032
PR    195836
RJ    328943
RN    113208
RO     46798
RR     14158
RS    186503
SC    110459
SE     78341
SP    751612
TO     37650
Name: count, dtype: int64

In [5]:
# Qual é a faixa etária dos participantes?

# Mapear os código de faixa etária
faixa_etaria = {1: "Menor de 17 anos",
                2: "17 anos",
                3: "18 anos", 
                4: "19 anos",
                5: "20 anos",
                6: "21 anos",
                7: "22 anos",
                8: "23 anos",
                9: "24 anos",
                10: "25 anos",
                11: "Entre 26 e 30 anos",
                12: "Entre 31 e 35 anos", 
                13: "Entre 36 e 40 anos",
                14: "Entre 41 e 45 anos",
                15: "Entre 46 e 50 anos",
                16: "Entre 51 e 55 anos",
                17: "Entre 56 e 60 anos",
                18: "Entre 61 e 65 anos",
                19: "Entre 66 e 70 anos",
                20: "Maior de 70 anos",
                }

df_partcipantes["TX_FAIXA_ETARIA"] = df_partcipantes["TP_FAIXA_ETARIA"].map(faixa_etaria)

(df_partcipantes[["TP_FAIXA_ETARIA", "TX_FAIXA_ETARIA"]]
 .groupby(["TP_FAIXA_ETARIA", "TX_FAIXA_ETARIA"], as_index=False)
 .value_counts()
 .sort_values(by="TP_FAIXA_ETARIA")
 )

    TP_FAIXA_ETARIA     TX_FAIXA_ETARIA    count
0                 1    Menor de 17 anos   578654
1                 2             17 anos  1021540
2                 3             18 anos  1151467
3                 4             19 anos   483303
4                 5             20 anos   271801
5                 6             21 anos   178368
6                 7             22 anos   133343
7                 8             23 anos   104839
8                 9             24 anos    87249
9                10             25 anos    74998
10               11  Entre 26 e 30 anos   253931
11               12  Entre 31 e 35 anos   150564
12               13  Entre 36 e 40 anos   113921
13               14  Entre 41 e 45 anos    84093
14               15  Entre 46 e 50 anos    54700
15               16  Entre 51 e 55 anos    34007
16               17  Entre 56 e 60 anos    19343
17               18  Entre 61 e 65 anos     9143
18               19  Entre 66 e 70 anos     3834
19               20    Maior de 70 anos     1674

In [6]:
# Qual é a quantidade de participantes por sexo?
df_sexo = df_partcipantes[["TP_SEXO"]].groupby(by="TP_SEXO", as_index=False).value_counts()
df_sexo["percentual"] = round(df_sexo['count'] / qtde_participantes * 100, 2)
df_sexo

  TP_SEXO    count  percentual
0       F  2889026       60.05
1       M  1921746       39.95

In [9]:
# Qual é a quantidade de participantes por raça?

raca = {0: "Não declarado",
        1: "Branca",
        2: "Preta",
        3: "Parda",
        4: "Amarela",
        5: "Indígena",
        }

df_partcipantes["TX_COR_RACA"] = df_partcipantes["TP_COR_RACA"].map(raca)

df_raca = (df_partcipantes[["TP_COR_RACA", "TX_COR_RACA"]]
           .groupby(["TP_COR_RACA", "TX_COR_RACA"], as_index=False)
           .value_counts()
           .sort_values("TP_COR_RACA")
           )
df_raca["percentual"] = round(df_raca["count"] / qtde_participantes * 100, 2)
df_raca

   TP_COR_RACA    TX_COR_RACA    count  percentual
0            0  Não declarado    54305        1.13
1            1         Branca  1902820       39.55
2            2          Preta   603032       12.54
3            3          Parda  2145936       44.61
4            4        Amarela    67199        1.40
5            5       Indígena    37480        0.78

In [12]:
# Quantos treineiros realizaram o ENEM 2025?
treineiro = {0: "Não", 1: "Sim"}

df_partcipantes["TX_TREINEIRO"] = df_partcipantes["IN_TREINEIRO"].map(treineiro)
df_treineiro = (df_partcipantes[["IN_TREINEIRO", "TX_TREINEIRO"]]
                .groupby(by=["IN_TREINEIRO", "TX_TREINEIRO"], as_index=False)
                .value_counts()
                )
df_treineiro["percentual"] = round(df_treineiro["count"] / qtde_participantes * 100, 2)
df_treineiro

   IN_TREINEIRO TX_TREINEIRO    count  percentual
0             0          Não  3823122       79.47
1             1          Sim   987650       20.53

#### Análise dos resultados das provas

In [13]:
df_resultados = pd.read_csv("../data/RESULTADOS_2025.csv", sep=";", encoding="iso-8859-1")
df_resultados.head()

,NU_SEQUENCIAL,NU_ANO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,NU_NOTA_COMP3_AV3,NU_NOTA_COMP4_AV3,NU_NOTA_COMP5_AV3,TP_STATUS_REDACAO_AV4,NU_NOTA_AV4,NU_NOTA_COMP1_AV4,NU_NOTA_COMP2_AV4,NU_NOTA_COMP3_AV4,NU_NOTA_COMP4_AV4,NU_NOTA_COMP5_AV4
0,206403,2025,33083592.0,3304557.0,Rio de Janeiro,33.0,RJ,2.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3604651,2025,21017115.0,2111300.0,São Luís,21.0,MA,2.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1461268,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4301058,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3148322,2025,35006207.0,3552205.0,Sorocaba,35.0,SP,4.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Qual é a nota média para cada tipo de área de conhecimento?
# Qual é a nota média da redação?
# Qual foi a maior e menor nota por área de conhecimento e redação? E a mediana?

df_notas = df_resultados[["NU_NOTA_CN", "NU_NOTA_CH", "NU_NOTA_LC", "NU_NOTA_MT", "NU_NOTA_REDACAO"]]
df_notas.describe().round(3)

        NU_NOTA_CN   NU_NOTA_CH   NU_NOTA_LC   NU_NOTA_MT  NU_NOTA_REDACAO
count  3260336.000  3457555.000  3457555.000  3260336.000      3457555.000
mean       499.974      511.189      532.123      519.982          580.804
std         78.586       88.259       72.637      127.637          212.865
min          0.000        0.000        0.000        0.000            0.000
25%        443.500      446.600      490.300      416.500          480.000
50%        498.200      513.000      538.800      500.000          600.000
75%        550.900      574.000      581.600      606.800          720.000
max        858.700      856.400      794.500      980.300         1000.000