## Análise Exploratória de Dados (EDA)
### Microdados ENEM 2025

In [2]:
import pandas as pd

In [3]:
df_partcipantes = pd.read_csv("../data/PARTICIPANTES_2025.csv", sep=";", encoding="iso-8859-1")
df_partcipantes.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,...,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023
0,210066506229,2025,6,F,1,2,2,1,4,NaN,...,A,A,A,A,A,A,A,A,B,A
1,210066506230,2025,3,M,1,1,1,2,0,1.0,...,A,B,B,A,C,A,B,B,B,A
2,210066506231,2025,2,F,1,1,1,3,0,NaN,...,A,A,B,A,A,A,B,C,C,C
3,210066506232,2025,2,M,1,3,2,2,0,1.0,...,A,B,A,A,B,A,B,B,D,D
4,210066506233,2025,1,F,1,1,1,3,0,NaN,...,B,B,B,B,D,B,B,D,E,D

In [ ]:
# Quantos participantes realizaram o ENEM 2025?
qtde_participantes = len(df_partcipantes)
print(f"Quantidade total de participantes: {qtde_participantes:,}")

Quantidade total de participantes: 4,810,772

In [14]:
# Qual a distribuição de participantes por Estado?
(df_partcipantes["SG_UF_PROVA"]
 .value_counts()
 .sort_index()
 )

SG_UF_PROVA
AC     28957
AL     96480
AM    110831
AP     33190
BA    427983
CE    275902
DF     82955
ES     85910
GO    166747
MA    211370
MG    464937
MS     57932
MT     80396
PA    289328
PB    142035
PE    272279
PI    120032
PR    195836
RJ    328943
RN    113208
RO     46798
RR     14158
RS    186503
SC    110459
SE     78341
SP    751612
TO     37650
Name: count, dtype: int64

In [ ]:
# Qual é a faixa etária dos participantes?

# Mapear os código de faixa etária
faixa_etaria = {1: "Menor de 17 anos",
                2: "17 anos",
                3: "18 anos", 
                4: "19 anos",
                5: "20 anos",
                6: "21 anos",
                7: "22 anos",
                8: "23 anos",
                9: "24 anos",
                10: "25 anos",
                11: "Entre 26 e 30 anos",
                12: "Entre 31 e 35 anos", 
                13: "Entre 36 e 40 anos",
                14: "Entre 41 e 45 anos",
                15: "Entre 46 e 50 anos",
                16: "Entre 51 e 55 anos",
                17: "Entre 56 e 60 anos",
                18: "Entre 61 e 65 anos",
                19: "Entre 66 e 70 anos",
                20: "Maior de 70 anos",
                }

df_partcipantes["TX_FAIXA_ETARIA"] = df_partcipantes["TP_FAIXA_ETARIA"].map(faixa_etaria)

(df_partcipantes[["TP_FAIXA_ETARIA", "TX_FAIXA_ETARIA"]]
 .groupby(["TP_FAIXA_ETARIA", "TX_FAIXA_ETARIA"], as_index=False)
 .value_counts()
 .sort_values(by="TP_FAIXA_ETARIA")
 )

    TP_FAIXA_ETARIA     TX_FAIXA_ETARIA    count
0                 1    Menor de 17 anos   578654
1                 2             17 anos  1021540
2                 3             18 anos  1151467
3                 4             19 anos   483303
4                 5             20 anos   271801
5                 6             21 anos   178368
6                 7             22 anos   133343
7                 8             23 anos   104839
8                 9             24 anos    87249
9                10             25 anos    74998
10               11  Entre 26 e 30 anos   253931
11               12  Entre 31 e 35 anos   150564
12               13  Entre 36 e 40 anos   113921
13               14  Entre 41 e 45 anos    84093
14               15  Entre 46 e 50 anos    54700
15               16  Entre 51 e 55 anos    34007
16               17  Entre 56 e 60 anos    19343
17               18  Entre 61 e 65 anos     9143
18               19  Entre 66 e 70 anos     3834
19               20    Maior de 70 anos     1674

In [ ]:
# Qual é a quantidade de participantes por sexo?
df_sexo = df_partcipantes[["TP_SEXO"]].groupby(by="TP_SEXO", as_index=False).value_counts()
df_sexo["percentual"] = round(df_sexo['count'] / qtde_participantes * 100, 2)
df_sexo

  TP_SEXO    count  percentual
0       F  2889026       60.05
1       M  1921746       39.95